@startuml

package presenter::view_models::shared::crossover_pattern_filter {
    enum CrossoverPatternFilter {
        GoldenOnly
        DeadOnly
        Both
    }

    CrossoverPatternFilter : +matches_filter(pattern: Pattern): bool
    CrossoverPatternFilter : +get_rate_of_chance(rate_of_chance: RateOfChance): f64
    CrossoverPatternFilter : +get_latest_chance(latest_chance: LatestChance): LatestChance
    CrossoverPatternFilter : +format_rate_of_chance_percent(rate_of_chance: RateOfChance): String
}

@enduml